### PR TITLE
Add new plotPrecursorIons function and address issue #742

### PR DESCRIPTION
**Pull request by jorainer**
In this PR:

- add new function `plotPrecursorIons` to visualize location of precursor ions in m/z - retention time plane.
- support exclusion of samples/groups from the definition of new features using the *PeakDensity* correspondence method (issue #742 ).

Unit tests and documentation included.

### CODE REVIEW

**Comment by jorainer** [comment]
@sneumann , I leave it up to you whether we want this small updates to be included in the upcoming release version or not...

**Review by philouail — APPROVED** [review]
All good to me ! really nice additions

**Comment by philouail** [comment]
Sorry @jorainer I just tested locally and realized something is wrong. 

Can you also update the *functions-Params.R* document (line 239) to allow for NAs in sampleGroups ?

**Comment by jorainer** [comment]
good catch @philouail ! I've changed it now.

**Comment by jorainer** [comment]
Changed to draft because there seem to be some problems...

**Comment by jorainer** [comment]
OK, now we have also a fix for a bug that Phili spotted when testing the code (although the bug was not related to the present code).

**Comment by jorainer** [comment]
@sneumann , can you please have a look at this PR and eventually merge if you're OK?

**Comment by sneumann** [comment]
Looks good, thanks! 
I haven't tested if there is any fallout if the `PeakDensityParam()` handling NAs in other downstream functions, like peak filling or plotting, is there any "worst-case" this could lead to unexpected/degenerate feature groups violating assumptions we take for granted ? 
Yours, Steffen

**Comment by jorainer** [comment]
There shouldn't be any issue - no other function/method uses this parameter - and the `PeakDensityParam()` handles it well - so, should be all good, thanks.

**Pull request merged**
