### PR TITLE
Jomain

### PR DESCRIPTION
**Pull request by jorainer**
This PR adds:
- `transformIntensity` function.
- fix issue #603

### CODE REVIEW

**Comment by jorainer** [comment]
@sneumann , can you please have a look at this PR, does not add much new things but fixes a bug/issue. If OK, please merge and push to BioC (along with the RELEASE_3_14 branch that contains the same fix).

**Comment by sneumann** [comment]
Looks good, and passes checks here. There is no unit test for #603, could one assemble such from the existing MS files ? Yours, Steffen

**Comment by jorainer** [comment]
you're right, there is none. AFAIK we don't have any (meaninful) MS1 and MS1+MS2 data in `msdata` we could use for that. I did test this locally on some of my data, but that's obviously not a *real* unit test.

**Comment by sneumann** [comment]
Maybe we can assemble a less meaningful test from existing mzMLs in msdata ?

**Pull request merged**
