### PR TITLE
changed error to warning when no peaks in ROI

### PR DESCRIPTION
**Pull request by stanstrup**
#90

### CODE REVIEW

**Comment by jotsetung** [comment]
Did `R CMD check` run without problems?
I would be in favor of this change, @sneumann what do you think?

**Comment by sneumann** [comment]
No objection from my side. @HendrikTreutler , does that affect your peak picking 
with predicted ROIs in any way ? Yours, Steffen

**Comment by stanstrup** [comment]
@jotsetung Yeah check has no complaints (related to this).

**Comment by Treutler** [comment]
I think the peak picking with predicted isotope ROIs is not affected. No objection from my side.

**Comment by jotsetung** [comment]
OK, next time `xcms3` gets merged into devel it will be fixed.

**Pull request merged**
