### PR TITLE
Addition of MzTabParam for export in .mztab format

### PR DESCRIPTION
**Pull request by philouail**
Here is the PR for the implementation of mztab-m export using the `storeResults` generic function combined with a param object of class `MzTabParam` . 

For now, the export format only has the mandatory field available (as well as possibility to add `opt_` columns for the SMF table. 
In the future more metadata rows could be implemented if it makes sense from the format of XcmsExperiment object. 

Any feedback and correction is welcomed.

### CODE REVIEW

**Comment by sneumann** [comment]
Hi, thanks for that PR! 

- [ ] Can you confirm the generated mzTab-M validates with https://apps.lifs-tools.org/mztabvalidator/ ?
- [x] Can you also confirm import works with `mztab <- MSnbase::MzTab(data_file)` ?
- [x] Can you check that MetaboAnalyst is happy: https://www.metaboanalyst.ca/MetaboAnalyst/upload/StatUploadView.xhtml
- [ ] Can you check that GNPS is happy: https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking-with-mztab-m/

Yours, Steffen

**Comment by jorainer** [comment]
So - the update of this PR was to remove all the mzTab related things now and just have a fix for the LamaParama? I would then suggest to maybe close this PR and open a new one specifically for that (describing the changes) @philouail .

**Comment by philouail** [comment]
I forgot that this was still open, super sorry about that. Will fix it.

**Comment by philouail** [comment]
Closing this PR as the `MzTabParam` method has been [moved](https://github.com/rformassspectrometry/MsIO)

**Pull request closed without merging**
