### PR TITLE
Adding support for weighted moving average from MALDIquant

### PR DESCRIPTION
**Pull request by SiggiSmara**
As explained in #235

### CODE REVIEW

**Comment by sgibb** [comment]
Depends on https://github.com/sgibb/MALDIquant/pull/54 and https://github.com/lgatto/MSnbase/pull/273/.

**Comment by SiggiSmara** [comment]
Looking at the code and the changes suggested in sgibb/MALDIquant#54 I think my changes here are actually not needed any more since the weighted moving average is being folded into the moving average function.

**Comment by jotsetung** [comment]
In case that's not needed anymore feel free to close @SiggiSmara

**Comment by SiggiSmara** [comment]
Not needed any more

**Pull request closed without merging**
