### PR TITLE
implemented function "do_predictIsotopeROIs"

### PR DESCRIPTION
**Pull request by Treutler**
corresponding to issue #82

split the functionality of "findPeaks.addPredictedIsotopeFeatures" / "findPeaks.centWaveWithPredictedIsotopeROIs" and implemented function "do_predictIsotopeROIs"

### CODE REVIEW

**Comment by jotsetung** [comment]
Looks great! Do you have any unit test checking that it does what is expected?

**Comment by Treutler** [comment]
There is an existing unit test for the full feature here:
xcms3/inst/unitTests/runit.findPeaksCentWaveWithIsotopeROIs.R

**Comment by jotsetung** [comment]
Great work! Thanks!

**Comment by Treutler** [comment]
I am happy to help. Thank you for your guidance!

**Pull request merged**
